server: 
    port: 8081

spring:
    datasource:
        url: jdbc:h2:mem:testdb
        username: sa
        password: password
        driverClassName: org.h2.Driver
    h2:
        console:
            enabled: true
            path: /h2
    jpa:
        hibernate:
            ddl-auto: create-drop